Sound/SoundDescriptor.o : Sound/SoundDescriptor.c Sound/SoundDescriptor.h Sound/Type_SoundDescriptor.h ../FileManager/FileManager.h ../Type_Bool.h
	gcc -c -o Sound/SoundDescriptor.o Sound/SoundDescriptor.c
BaseDescriptor.o : BaseDescriptor.c BaseDescriptor.h Sound/SoundDescriptor.h Type_FileType.h Type_BaseDescriptor.h ../Type_Bool.h
